name: "release"

on:
  push:
    tags:
      - "release-*"

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Install Dependencies"
        run: npm install
      - name: "Build"
        run: npm run build
      - name: "Create Binaries"
        run: "npm run export-releases"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*
