name: "binary release"

on:
  push:
    tags:
      - "release-*"
      - "test-*"

jobs:
  windows-release:
    name: "Windows Binary Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Install Dependencies"
        run: npm install
      - name: "Build"
        run: npm run build
      - name: "Create Windows Binary"
        run: |
          npx pkg -t node16 --out-path binaries dist/image-compressor.js
          mkdir binaries/sharp
          Copy-Item -Recurse -Path "./node_modules/sharp/vendor", "./node_modules/sharp/build" -Destination "./binaries/sharp"
          Compress-Archive -Path .\binaries\ -DestinationPath image-compressor-win.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: image-compressor-*

  linux-release:
    name: "Linux Binary Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Install Dependencies"
        run: npm install
      - name: "Build"
        run: npm run build
      - name: "Create Linux Binary"
        run: |
          npx pkg -t node16 --out-path binaries dist/image-compressor.js
          mkdir binaries/sharp
          cp -R ./node_modules/sharp/vendor ./node_modules/sharp/build ./binaries/sharp
          zip -r image-compressor-linux.zip ./binaries
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: image-compressor-*
  macos-release:
    name: "Mac Binary Release"
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Install Dependencies"
        run: npm install
      - name: "Build"
        run: npm run build
      - name: "Create Mac Binary"
        run: |
          npx pkg -t node16 --out-path binaries dist/image-compressor.js
          mkdir binaries/sharp 
          cp -R ./node_modules/sharp/vendor ./node_modules/sharp/build ./binaries/sharp
          zip -r image-compressor-mac.zip ./binaries
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: image-compressor-*
